config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :homepage_products do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end
  end
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/homepage_product.rb
class Spree::HomepageProduct < ActiveRecord::Base
  belongs_to :product
  validates_uniqueness_of :product_id
end

app/models/spree/product_decorator.rb
module Spree
  Product.class_eval do
    has_many :homepage_products, dependent: :destroy
  end
end

app/controllers/spree/admin/homepage_products_controller.rb
module Spree
  module Admin
    class HomepageProductsController < ResourceController
      def index
      end

      def new
      end
    end
  end
end

app/controllers/spree/home_controller_decorator.rb
module Spree
  HomeController.class_eval do
    def index
      @products = HomepageProduct.order(:position).map(&:product)
    end
  end
end

app/helpers/spree/admin/homepage_products_helper.rb
module Spree::Admin::HomepageProductsHelper
end

app/views/spree/admin/homepage_products/_form.html.erb
<div data-hook="admin_homepage_product_form_fields" class="align-center row">

  <div class="alpha sixteen omega columns">
    <%= f.field_container :product do %>
      <%= f.label :product, Spree.t(:product) %> <span class="required">*</span><br />
      <%= f.select :product_id, Spree::Product.all.collect {|p| [ p.name, p.id ] }, { include_blank: false }, :class => "fullwidth" %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

</div>

app/views/spree/admin/homepage_products/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:homepage_products) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_ot_link">
    <%= button_link_to Spree.t(:new_homepage_products), new_admin_homepage_product_url, { :remote => true, :icon => 'icon-plus', :id => 'new_homepage_product_link' } %>
  </li>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<div id="new_homepage_product"></div>

<% if @homepage_products.any? %>
<table class="index sortable" id="listing_option_types" data-hook data-sortable-link="<%= update_positions_admin_homepage_products_url %>">
  <colgroup>
    <col style="width: 10%">
    <col style="width: 75%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="option_header">
      <th class="no-border"></th>
      <th><%= Spree.t(:product) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @homepage_products.each do |homepage_product| %>
      <tr class="spree_option_type <%= cycle('odd', 'even')%>" id="<%= spree_dom_id homepage_product %>" data-hook="option_row">
        <td class="no-border"><span class="handle"></span></td>
        <td class="align-center"><%= homepage_product.product.name %></td>
        <td class="actions">
          <%= link_to_delete(homepage_product, :no_text => true) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/homepage_product')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_homepage_product_path %>!
  </div>
<% end %>

app/views/spree/admin/homepage_products/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @homepage_product } %>

<%= form_for [:admin, @homepage_product] do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t(:new_homepage_product) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/homepage_products/new.js.erb
$("#new_homepage_product").html('<%= escape_javascript(render :template => "spree/admin/homepage_products/new", :formats => [:html], :handlers => [:erb]) %>');
$("#new_homepage_product_link").parent().hide();